    FROM node:18.12.1-buster

    WORKDIR /app

    COPY package.json package.json
    COPY package-lock.json package-lock.json

    RUN npm install 

    COPY . .
    ENV CHOKIDAR_USEPOLLING=true
    EXPOSE 3000 

    CMD ["npm","start"]

